title: 欸欸
description: 谢谢我喜欢你
author:
  name: 欸欸

remote_theme: hmua/Customized-Minima
permalink: /:categories/:year/:i_month/:i_day/:title #网址，不在月日前加零，结尾什么都不加

# Markdown之外，目录、首页、正文外格式
show_excerpts: true #首页显示节选

collections: 
    星座: 
        output: true
